[package]
name = "cmt"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
git2 = "0.20.0"
serde = { version= "1.0.217", features = ["derive"] }
toml = "0.8.20"
directories = "6.0.0"
clap =  { version = "4.5.30", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"